# Generated by Django 5.1.4 on 2024-12-11 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oc_lettings_site", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="letting",
                    name="address",
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Address",
                ),
            ],
            # Rename table
            database_operations=[
                migrations.AlterModelTable(
                    name="Address", table="lettings_address"
                )
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Letting",
                ),
            ],
            # Rename table
            database_operations=[
                migrations.AlterModelTable(
                    name="Letting", table="lettings_letting"
                )
            ],
        ),
    ]
