name: Test and Lint

on: [push]

jobs:
  test-and-linting:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Check out code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13.0

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run tests with coverage check
    - name: Run tests and check coverage
      run: |
        pytest --cov=./
        coverage report --fail-under=80

    # Step 5: Run flake8 linting
    - name: Lint with flake8
      run: |
        flake8 --count --statistics
